"""
Alpha-Lab: Analysis Suite for Alpha Signal Research

This package provides comprehensive analysis and visualization tools
for alpha signals generated by alpha-canvas.

Core Features:
- Performance Metrics (L1): Sharpe, volatility, drawdown, turnover, etc.
- PnL Tracing (L2): Step-by-step signal evolution and comparison
- Visualization (V1-V3): Heatmaps, PnL curves, attribution charts
- Advanced Analytics (A1-A3): Factor exposure, IC analysis, sensitivity

Design Principles:
- Loosely coupled with alpha-canvas via public APIs
- Jupyter-first: Interactive plots + raw data access
- Pluggable analyzers and visualizers
- No internal access to Expression trees or Visitor

Usage:
    from alpha_lab import PerformanceAnalyzer, PnLTracer, Visualizer
    
    # Analyze performance metrics
    analyzer = PerformanceAnalyzer()
    metrics = analyzer.compute_metrics(
        port_returns=rc.get_port_return(step=2),
        frequency='daily'
    )
    
    # Compare steps
    tracer = PnLTracer()
    comparison = tracer.compare_steps(
        rc, steps=[0, 1, 2], metric='sharpe'
    )
    
    # Visualize PnL evolution
    viz = Visualizer()
    viz.plot_pnl_curves(rc, steps=[0, 1, 2])
"""

__version__ = "0.1.0"

# Public API placeholder - will be implemented later
__all__ = [
    # "PerformanceAnalyzer",  # TODO: Implement L1 (MVP)
    # "PnLTracer",            # TODO: Implement L2 (MVP)
    # "Visualizer",           # TODO: Implement V1-V3 (Future)
]

